'use client'
import "./globals.css"

// Components
import Navbar from './components/Navbar';
import Footer from './components/Footer';

import { AuthContextProvider } from "./context/AuthContext";

export const metadata = {
  title: 'FireBase App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider> 
          <div className="App">
            <Navbar />
              <div className="container">
                {children}
              </div>
            <Footer />
          </div>
        </AuthContextProvider>
      </body>
    </html>
  )
}
